PROG=proj

SRCS = proj.c bitmap.c keyboard.c mouse_test.c video_gr.c timer.c game.c main_menu.c initGame.c

CPPFLAGS += -pedantic #-D __LCOM_OPTIMIZED__

DPADD += ${LIBLCF}
LDADD += -llcf

.include <minix.lcom.mk>
